[package]
name = "pushback"
version = "0.1.0"
authors = ["ankitb"]

[lib]
crate-type = ["dylib"]

[dependencies]
quote        = "= 1.0.9"
proc-macro2  = "= 1.0.26"
serde        = "= 1.0.37"
serde_derive = "= 1.0.37"
db        = { path = "../../db" }
sandstorm = { path = "../../sandstorm" }
